// Code generated by MockGen. DO NOT EDIT.
// Source: crypto-screener/internal/domain (interfaces: ExchangeConnector,FundingSink,TelegramSender,SignalRepository,UserRepository,CommandHandler,VolumeProvider)
//
// Generated by this command:
//
//	mockgen -destination internal/domain/mocks/mock_ports.go -package mocks crypto-screener/internal/domain ExchangeConnector,FundingSink,TelegramSender,SignalRepository,UserRepository,CommandHandler,VolumeProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "crypto-screener/internal/domain"
	reflect "reflect"
	time "time"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockExchangeConnector is a mock of ExchangeConnector interface.
type MockExchangeConnector struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeConnectorMockRecorder
	isgomock struct{}
}

// MockExchangeConnectorMockRecorder is the mock recorder for MockExchangeConnector.
type MockExchangeConnectorMockRecorder struct {
	mock *MockExchangeConnector
}

// NewMockExchangeConnector creates a new mock instance.
func NewMockExchangeConnector(ctrl *gomock.Controller) *MockExchangeConnector {
	mock := &MockExchangeConnector{ctrl: ctrl}
	mock.recorder = &MockExchangeConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeConnector) EXPECT() *MockExchangeConnectorMockRecorder {
	return m.recorder
}

// ConnectFunding mocks base method.
func (m *MockExchangeConnector) ConnectFunding(ctx context.Context, sink domain.FundingSink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectFunding", ctx, sink)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectFunding indicates an expected call of ConnectFunding.
func (mr *MockExchangeConnectorMockRecorder) ConnectFunding(ctx, sink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectFunding", reflect.TypeOf((*MockExchangeConnector)(nil).ConnectFunding), ctx, sink)
}

// ConnectFutures mocks base method.
func (m *MockExchangeConnector) ConnectFutures(ctx context.Context, outChan chan<- domain.MarketTick) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectFutures", ctx, outChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectFutures indicates an expected call of ConnectFutures.
func (mr *MockExchangeConnectorMockRecorder) ConnectFutures(ctx, outChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectFutures", reflect.TypeOf((*MockExchangeConnector)(nil).ConnectFutures), ctx, outChan)
}

// ConnectSpot mocks base method.
func (m *MockExchangeConnector) ConnectSpot(ctx context.Context, outChan chan<- domain.MarketTick) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectSpot", ctx, outChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectSpot indicates an expected call of ConnectSpot.
func (mr *MockExchangeConnectorMockRecorder) ConnectSpot(ctx, outChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectSpot", reflect.TypeOf((*MockExchangeConnector)(nil).ConnectSpot), ctx, outChan)
}

// MockFundingSink is a mock of FundingSink interface.
type MockFundingSink struct {
	ctrl     *gomock.Controller
	recorder *MockFundingSinkMockRecorder
	isgomock struct{}
}

// MockFundingSinkMockRecorder is the mock recorder for MockFundingSink.
type MockFundingSinkMockRecorder struct {
	mock *MockFundingSink
}

// NewMockFundingSink creates a new mock instance.
func NewMockFundingSink(ctrl *gomock.Controller) *MockFundingSink {
	mock := &MockFundingSink{ctrl: ctrl}
	mock.recorder = &MockFundingSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFundingSink) EXPECT() *MockFundingSinkMockRecorder {
	return m.recorder
}

// UpdateFunding mocks base method.
func (m *MockFundingSink) UpdateFunding(exchange, symbol string, rate decimal.Decimal, nextTime, eventTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFunding", exchange, symbol, rate, nextTime, eventTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFunding indicates an expected call of UpdateFunding.
func (mr *MockFundingSinkMockRecorder) UpdateFunding(exchange, symbol, rate, nextTime, eventTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFunding", reflect.TypeOf((*MockFundingSink)(nil).UpdateFunding), exchange, symbol, rate, nextTime, eventTime)
}

// SetStreamHealth mocks base method.
func (m *MockFundingSink) SetStreamHealth(exchange string, healthy bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamHealth", exchange, healthy)
}

func (mr *MockFundingSinkMockRecorder) SetStreamHealth(exchange, healthy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamHealth", reflect.TypeOf((*MockFundingSink)(nil).SetStreamHealth), exchange, healthy)
}

// MockTelegramSender is a mock of TelegramSender interface.
type MockTelegramSender struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramSenderMockRecorder
	isgomock struct{}
}

// MockTelegramSenderMockRecorder is the mock recorder for MockTelegramSender.
type MockTelegramSenderMockRecorder struct {
	mock *MockTelegramSender
}

// NewMockTelegramSender creates a new mock instance.
func NewMockTelegramSender(ctrl *gomock.Controller) *MockTelegramSender {
	mock := &MockTelegramSender{ctrl: ctrl}
	mock.recorder = &MockTelegramSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramSender) EXPECT() *MockTelegramSenderMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockTelegramSender) Broadcast(text string, chatIDs []int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", text, chatIDs)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockTelegramSenderMockRecorder) Broadcast(text, chatIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockTelegramSender)(nil).Broadcast), text, chatIDs)
}

// Close mocks base method.
func (m *MockTelegramSender) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockTelegramSenderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTelegramSender)(nil).Close))
}

// SendPrivateMessage mocks base method.
func (m *MockTelegramSender) SendPrivateMessage(chatID int64, text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendPrivateMessage", chatID, text)
}

// SendPrivateMessage indicates an expected call of SendPrivateMessage.
func (mr *MockTelegramSenderMockRecorder) SendPrivateMessage(chatID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPrivateMessage", reflect.TypeOf((*MockTelegramSender)(nil).SendPrivateMessage), chatID, text)
}

// MockSignalRepository is a mock of SignalRepository interface.
type MockSignalRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSignalRepositoryMockRecorder
	isgomock struct{}
}

// MockSignalRepositoryMockRecorder is the mock recorder for MockSignalRepository.
type MockSignalRepositoryMockRecorder struct {
	mock *MockSignalRepository
}

// NewMockSignalRepository creates a new mock instance.
func NewMockSignalRepository(ctrl *gomock.Controller) *MockSignalRepository {
	mock := &MockSignalRepository{ctrl: ctrl}
	mock.recorder = &MockSignalRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalRepository) EXPECT() *MockSignalRepositoryMockRecorder {
	return m.recorder
}

// SaveSignal mocks base method.
func (m *MockSignalRepository) SaveSignal(ctx context.Context, signal *domain.ArbitrageSignal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSignal", ctx, signal)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSignal indicates an expected call of SaveSignal.
func (mr *MockSignalRepositoryMockRecorder) SaveSignal(ctx, signal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSignal", reflect.TypeOf((*MockSignalRepository)(nil).SaveSignal), ctx, signal)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// DeleteUser mocks base method.
func (m *MockUserRepository) DeleteUser(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepositoryMockRecorder) DeleteUser(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepository)(nil).DeleteUser), ctx, chatID)
}

// GetAllUsers mocks base method.
func (m *MockUserRepository) GetAllUsers(ctx context.Context) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserRepositoryMockRecorder) GetAllUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserRepository)(nil).GetAllUsers), ctx)
}

// SaveUser mocks base method.
func (m *MockUserRepository) SaveUser(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserRepositoryMockRecorder) SaveUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserRepository)(nil).SaveUser), ctx, user)
}

// MockCommandHandler is a mock of CommandHandler interface.
type MockCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommandHandlerMockRecorder
	isgomock struct{}
}

// MockCommandHandlerMockRecorder is the mock recorder for MockCommandHandler.
type MockCommandHandlerMockRecorder struct {
	mock *MockCommandHandler
}

// NewMockCommandHandler creates a new mock instance.
func NewMockCommandHandler(ctrl *gomock.Controller) *MockCommandHandler {
	mock := &MockCommandHandler{ctrl: ctrl}
	mock.recorder = &MockCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandHandler) EXPECT() *MockCommandHandlerMockRecorder {
	return m.recorder
}

// HandleCommand mocks base method.
func (m *MockCommandHandler) HandleCommand(chatID int64, username, cmd string, args []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCommand", chatID, username, cmd, args)
	ret0, _ := ret[0].(string)
	return ret0
}

// HandleCommand indicates an expected call of HandleCommand.
func (mr *MockCommandHandlerMockRecorder) HandleCommand(chatID, username, cmd, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCommand", reflect.TypeOf((*MockCommandHandler)(nil).HandleCommand), chatID, username, cmd, args)
}

// MockVolumeProvider is a mock of VolumeProvider interface.
type MockVolumeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeProviderMockRecorder
	isgomock struct{}
}

// MockVolumeProviderMockRecorder is the mock recorder for MockVolumeProvider.
type MockVolumeProviderMockRecorder struct {
	mock *MockVolumeProvider
}

// NewMockVolumeProvider creates a new mock instance.
func NewMockVolumeProvider(ctrl *gomock.Controller) *MockVolumeProvider {
	mock := &MockVolumeProvider{ctrl: ctrl}
	mock.recorder = &MockVolumeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeProvider) EXPECT() *MockVolumeProviderMockRecorder {
	return m.recorder
}
